#!/usr/bin/env python3
"""
Split source_blocks.md into chunk files for safe, no-omissions translation.

Input:
  - source_blocks.md (generated by build_source_blocks.py)

Outputs:
  - translation_inputs/chunk_001.md, chunk_002.md, ...

Chunk format:
  <!-- id: ... type: ... -->
  ZH: <original Chinese block>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


ID_RE = re.compile(r"^<!-- id: ([pt]\d{6}) type: (paragraph|table_row) -->\s*$")


def parse_blocks(source_md: str) -> list[tuple[str, str, str]]:
    """
    Return list of (id, type, zh_text).
    """
    lines = source_md.splitlines()
    blocks: list[tuple[str, str, str]] = []
    i = 0
    while i < len(lines):
        m = ID_RE.match(lines[i].strip())
        if not m:
            i += 1
            continue
        bid, btype = m.group(1), m.group(2)
        i += 1
        # Skip optional context comment(s)
        while i < len(lines) and lines[i].strip().startswith("<!-- context:"):
            i += 1
        # Capture text until blank line
        text_lines: list[str] = []
        while i < len(lines) and lines[i].strip() != "":
            text_lines.append(lines[i])
            i += 1
        # consume blank lines
        while i < len(lines) and lines[i].strip() == "":
            i += 1
        zh = "\n".join(text_lines).strip()
        blocks.append((bid, btype, zh))
    return blocks


def write_chunks(blocks: list[tuple[str, str, str]], out_dir: Path, max_chars: int) -> int:
    out_dir.mkdir(parents=True, exist_ok=True)
    chunk = 0
    current: list[tuple[str, str, str]] = []
    current_chars = 0

    def flush() -> None:
        nonlocal chunk, current, current_chars
        if not current:
            return
        chunk += 1
        out_path = out_dir / f"chunk_{chunk:03d}.md"
        with out_path.open("w", encoding="utf-8") as f:
            f.write("# Translation input\n\n")
            f.write("Translate every block. Preserve IDs exactly. Do not summarize.\n\n")
            for bid, btype, zh in current:
                f.write(f"<!-- id: {bid} type: {btype} -->\n")
                f.write("ZH: " + zh.replace("\n", "\nZH: ") + "\n\n")
        current = []
        current_chars = 0

    for bid, btype, zh in blocks:
        entry = (bid, btype, zh)
        entry_chars = len(zh) + 40
        if current and current_chars + entry_chars > max_chars:
            flush()
        current.append(entry)
        current_chars += entry_chars

    flush()
    return chunk


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("Usage: make_translation_chunks.py <source_blocks.md> [max_chars]", file=sys.stderr)
        return 2
    source_path = Path(argv[1]).expanduser().resolve()
    max_chars = int(argv[2]) if len(argv) >= 3 else 12000
    text = source_path.read_text(encoding="utf-8")
    blocks = parse_blocks(text)
    out_dir = source_path.parent / "translation_inputs"
    n = write_chunks(blocks, out_dir=out_dir, max_chars=max_chars)
    print(f"Wrote {n} chunks to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))

