# TRETC Bios

## John Franolich
Slippery Rock University

John Franolich has 20 years of security experience and has worked in every industry vertical. Successful AI projects John has led include securing Google Cloud Platform for an FDA-regulated digital Radiology Type I Medical Device and Financial Modeling in secure Microsoft Azure environments for a large financial institution. John currently works for a global corporation doing cyber threat intelligence investigating cyber criminals and nation state actors. Additionally, John is actively researching the use of Retrieval Augmentation Generation in LLMs to enhance cyber threat hunting and Agentic AI, and MCP using large sets of metadata to do attacker attribution. John has a Master's degree in Information Assurance from The University of Pittsburgh and is a GIAC Certified Forensics Analyst (GCFA). He has taught Computer Security, Malware Analysis, and IT Forensics in a university setting since 2010. John also served a six-year tenure as the President of the ISC2 Pittsburgh Chapter.


## Zachary Jones
Keystone Flow

Zachary Jones has served across software architecture and security roles, most recently as Chief Product Officer at Apacen - designing immersive cybersecurity workflow tools, and AI systems that enhance cognitive bandwidth for human-AI collaboration. His work has included developing ontologies and ontology-hydration frameworks across a variety of industry contexts. Zak has over 15 years of experience spanning data systems, applications and platforms, XR interfaces, blockchain, security architecture, fintech, and AI / LLMs. He has led training programs for Fortune 500 organizations, served on the Arizona State Education Engineering Standards Committee, and is a published author and technical speaker. Zak has a masters and bachelors in HCI from Carnegie Mellon and Arizona State, combined with hands-on experience building machine learning pipelines, semantic knowledge systems, and educational platforms.
